kind: pipeline
name: default

steps:
- name: docker-dr
  image: plugins/docker
  settings:
    repo: jeffail/benthos-lab
    dry_run: true
  when:
    event: [ pull_request ]

- name: docker
  image: plugins/docker
  settings:
    repo: jeffail/benthos-lab
    auto_tag: true
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: [ push, tag ]
