kind: pipeline
name: default

steps:
- name: deps
  image: golang:1.12
  environment:
    GO111MODULE: on
  commands:
    - go mod vendor

- name: docker-dr
  image: plugins/docker
  settings:
    repo: jeffail/benthos-lab
    dry_run: true
  when:
    event: [ push, pull_request ]

- name: docker
  image: plugins/docker
  settings:
    repo: jeffail/benthos-lab
    auto_tag: true
    username: jeffail
    password:
      from_secret: docker_password
  when:
    event: tag
